# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '__first__'),
        ('department', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('issue', models.BooleanField(default=False)),
                ('issue_count', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('user_room', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_complaints', to='department.Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_complaints', to='department.Employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_complaints', to=settings.AUTH_USER_MODEL)),
                ('user_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_complaints', to='hostel.Block')),
                ('user_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_complaints', to='hostel.Floor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together=set([('slug', 'status')]),
        ),
    ]
