# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 05:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '__first__'),
        ('hostel', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('issue', models.BooleanField(default=False)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('user_room', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='department.Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='department.Employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('user_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='hostel.Block')),
                ('user_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='hostel.Floor')),
            ],
            options={
                'permissions': (('view_his_complaints', 'Can View his own complaint'), ('change_his_complaints', 'Can change his own complaints'), ('delete_his_complaints', 'Can Delete his own complaints'), ('view_floor_complaints', 'Can view all complaints in the floor'), ('view_block_complaints', 'Can View all complaints in the Block')),
            },
        ),
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together=set([('slug', 'status')]),
        ),
    ]
