# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'permissions': (('view_his_complaints', 'Can View his own complaint'), ('change_his_complaints', 'Can change his own complaints'), ('delete_his_complaints', 'Can Delete his own complaints'), ('view_floor_complaints', 'Can view all complaints in the floor'), ('view_block_complaints', 'Can View all complaints in the Block'))},
        ),
    ]
