# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_auto_20171022_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user_room',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
