# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 07:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_auto_20171022_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='department.Department'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='department.Employee'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='hostel.Block'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user_floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='hostel.Floor'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user_room',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
