# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_auto_20171022_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='user_floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exicomplaints', to='hostel.Floor'),
        ),
    ]
