# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-21 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='hostel.Block'),
        ),
        migrations.AlterField(
            model_name='user',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='hostel.Floor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='room_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
