# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171021_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='hostel.Block'),
        ),
        migrations.AlterField(
            model_name='user',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='hostel.Floor'),
        ),
    ]
