# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171022_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
