# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_letter', models.CharField(choices=[('a', 'Name of A block'), ('b', 'Name of B block'), ('c', 'Name of C block'), ('d', 'Name of D block'), ('e', 'Name of E block'), ('f', 'Name of F block'), ('g', 'Name of G block'), ('h', 'Name of F block'), ('j', 'Name of J block')], default='a', max_length=3, unique=True)),
                ('name', models.CharField(blank=True, max_length=125)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.PositiveIntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_floors', to='hostel.Block')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together=set([('block', 'floor_number')]),
        ),
    ]
