# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_letter',
            field=models.CharField(choices=[('a', 'Name of A block'), ('b', 'Name of B block'), ('c', 'Name of C block'), ('d', 'Name of D block'), ('e', 'Name of E block'), ('f', 'Name of F block'), ('g', 'Name of G block'), ('h', 'Name of F block'), ('j', 'Name of J block')], default='a', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='block',
            name='slug',
            field=models.SlugField(),
        ),
    ]
