# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_auto_20170921_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name='block',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
