# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 17:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=125)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10}$')])),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_employees', to='department.Department')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_employees', to='department.Department')),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_employees', to='department.Department')),
            ],
        ),
    ]
