# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_employees', to='hostel.Block'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_employees', to='hostel.Floor'),
        ),
    ]
