# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20171022_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_employees', to='hostel.Floor'),
        ),
    ]
